name: Ping Reviewers
on:
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

concurrency:
  group: ping
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ping reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          python ping_reviewers.py
